package ovh.heraud.nativsql.util;

/**
 * Enumeration of SQL operators used in WHERE conditions.
 *
 * This enum encapsulates both:
 * 1. The SQL operator name (e.g., "=", "IN")
 * 2. A WhereExpressionBuilder strategy that defines how to generate the SQL expression for that operator
 *
 * Design Pattern: Strategy + Enum Pattern
 * - Each operator is a constant that holds both its SQL representation and its expression generation logic
 * - This eliminates the need for large switch/case statements elsewhere in the code
 *
 * How it fits in the data flow:
 * 1. User calls: whereClause.add("status", Operator.EQUALS, "ACTIVE")
 * 2. A Condition is created and stored: new Condition("status", Operator.EQUALS, "ACTIVE")
 * 3. When building the WHERE clause, WhereClause.build() iterates through conditions:
 *    - Gets the Condition's Operator
 *    - Gets the WhereExpressionBuilder from that Operator
 *    - Calls buildExpression(dbColumn, paramName) to get the SQL fragment
 *    - Joins all fragments with " AND " to create the full WHERE clause
 *
 * Example lifecycle:
 * whereClause.add("user_id", Operator.EQUALS, 123)
 *   ↓
 * Condition("user_id", Operator.EQUALS, 123) stored in conditions list
 *   ↓
 * During build():
 *   - condition.getOperator() → Operator.EQUALS
 *   - condition.getOperator().getExpressionBuilder() → lambda (col, param) → col + " = :" + param
 *   - expressionBuilder.buildExpression("user_id", "userId") → "user_id = :userId"
 *   ↓
 * Result appended to WHERE clause
 */
public enum Operator {
    EQUALS("=", (col, param) -> col + " = :" + param),
    IN("IN", (col, param) -> col + " IN (:" + param + ")");

    private final String sql;
    private final WhereExpressionBuilder expressionBuilder;

    Operator(String sql, WhereExpressionBuilder expressionBuilder) {
        this.sql = sql;
        this.expressionBuilder = expressionBuilder;
    }

    /**
     * Returns the SQL operator symbol/name.
     * Example: "=" for EQUALS, "IN" for IN
     * Note: This is mainly for reference; the actual SQL is generated by WhereExpressionBuilder.
     *
     * @return the SQL operator name
     */
    public String getSql() {
        return sql;
    }

    /**
     * Returns the strategy for building this operator's SQL expression.
     * Callers use this to generate the complete SQL expression for a specific column and parameter.
     *
     * Example usage:
     * Operator.EQUALS.getExpressionBuilder()
     *     .buildExpression("user_id", "userId")
     *     → returns "user_id = :userId"
     *
     * @return the WhereExpressionBuilder strategy for this operator
     */
    public WhereExpressionBuilder getExpressionBuilder() {
        return expressionBuilder;
    }
}
