# Logging
logging.level.org.springframework.jdbc=DEBUG
logging.level.ovh.heraud.nativsql.repository=DEBUG

# Logging patterns
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{35} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n