-- Test schema initialization for Oracle
-- Creates all necessary types and tables for testing

CREATE TABLE user_group (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(255),
    last_name VARCHAR2(255),
    email VARCHAR2(255) UNIQUE NOT NULL,
    external_id CHAR(36) UNIQUE,
    status VARCHAR2(50) CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    address CLOB,
    age NUMBER(19,0),
    preferences CLOB,
    group_id NUMBER(19,0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES user_group(id) ON DELETE SET NULL
);

CREATE TABLE contact_info (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19,0) NOT NULL,
    contact_type VARCHAR2(50) NOT NULL CHECK (contact_type IN ('EMAIL', 'PHONE', 'FACEBOOK', 'TWITTER', 'LINKEDIN', 'WEBSITE')),
    contact_value VARCHAR2(255) NOT NULL,
    is_primary NUMBER(1,0) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_users_status ON users(status);
CREATE INDEX idx_users_group_id ON users(group_id);
CREATE INDEX idx_contact_info_user_id ON contact_info(user_id);
CREATE INDEX idx_contact_info_type ON contact_info(contact_type);

-- Test tables for each data type
CREATE TABLE data_type_long (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data NUMBER(19,0)
);

CREATE TABLE data_type_integer (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data NUMBER(10,0)
);

CREATE TABLE data_type_double (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data BINARY_DOUBLE
);

CREATE TABLE data_type_float (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data BINARY_FLOAT
);

CREATE TABLE data_type_short (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data NUMBER(5,0)
);

CREATE TABLE data_type_byte (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data NUMBER(3,0)
);

CREATE TABLE data_type_big_decimal (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data NUMBER(19,10)
);

CREATE TABLE data_type_big_integer (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data NUMBER(19,0)
);

CREATE TABLE data_type_boolean (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data NUMBER(1,0)
);

CREATE TABLE data_type_string (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data VARCHAR2(255)
);

CREATE TABLE data_type_uuid (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data CHAR(36)
);

CREATE TABLE data_type_local_date (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE
);

CREATE TABLE data_type_local_datetime (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TIMESTAMP
);

CREATE TABLE data_type_byte_array (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data BLOB
)
